# redis服务器配置
spring:
  redis:
    database: 0
    host: 192.168.31.233
    port: 6379
    lettuce:
      pool:
        min-idle: 20000
        max-active: 20000
  datasource:
    url: jdbc:mysql://192.168.31.233:3306/test?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 10000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
